### ISSUE TITLE
Remove Guides on export.

### ISSUE THREAD

**Issue by made-you-look** [hsw107/Photoshop-Export-Layers-to-Files-Fast#123]
Fantastic script, just what I was looking for!

I've come across an issue though.
I have a psd with 25 layers. The psd has guides set up.
After export, open individual files, in my case a jpg in photoshop, the guides from the original psd file are still there.

A work around currently is to clear guides before export, export, return guides, re-save.

Not ideal, but works.

Would be nice to have this script not save the guides, or have an option to clear guides.

Thanks!

**Comment by hsw107** [comment]
@made-you-look This looks to be just how Photoshop does it (as of CC 2014 I believe), and it does not have anything to do with our script. Thanks!
