### ISSUE TITLE
Trim Each Layer

### ISSUE THREAD

**Issue by DanielThomasArt** [hsw107/Photoshop-Export-Layers-to-Files-Fast#124]
With the latest script and the latest PS CC 2019 20.0.0.

When trying to use 'trim each layer' selected the script only exports out 2-4 images and them stops. Also, the 2-4 image exported has their size cropped to the first image exported.

I tried with different PSD files and changing around the other settings, the same result.

I tried an older version of the script from two years ago and it works correctly.

**Comment by LittleGreenDog** [comment]
All my images are getting exported with the new script but I'm seeing the same trimming problem. The older script did not have this problem.

Thanks for continuing to develop this plugin! I've been wanting overwrite for a long time. Fix the above and the script will be perfect for me. :)

**Comment by hsw107** [comment]
@DanielThomasArt / @LittleGreenDog Thanks for reporting this issue. It should now be fixed. Let me know if you encounter any other issues around this.
