### ISSUE TITLE
addPadding() of "1 px" creates massive image

### ISSUE THREAD

**Issue by mlsad3** [hsw107/Photoshop-Export-Layers-to-Files-Fast#125]
This is on CS6. I have a canvas of size 2106x1362 pixels, and when I run the script, it makes the canvas MASSIVE. Orders of magnitude larger. After trying to save the image for several minutes, it fails when the scratch disk runs out of space

The following menu selections are made:
- Export: all layers
- Trim: Each layer
- Padding: Add padding: "1" px
- File type: PNG-24 (Transparency)

I wonder if the addPadding() code needs some units?
`app.activeDocument.resizeCanvas(width, height, AnchorPosition.MIDDLECENTER);`

**Comment by mlsad3** [comment]
Here is the image that I have this issue with

![untitled-1](https://user-images.githubusercontent.com/15711477/49734183-b6d02180-fc40-11e8-9d26-cf83e9d15914.png)

**Comment by hsw107** [comment]
That seems to have been the problem, let me know if it's fixed now, thanks!

**Comment by mlsad3** [comment]
Awesome, that works now! Thanks much!
