### ISSUE TITLE
Suffix always adds a -

### ISSUE THREAD

**Issue by niels9001** [hsw107/Photoshop-Export-Layers-to-Files-Fast#128]
I'm trying to achieve the following:

Layer-name: **Lightbulb**
Suffix: **.scale-100**
Output type: **.png**

I would expect, that the generated output would be Lightbulb.scale-100.png, however the actual result is Lightbulb**-**.scale-100.png. Is there a way to remove the extra - in the UI so it's excluded?

**Comment by hsw107** [comment]
Unfortunately there's not a way to do this today!

**Comment by hsw107** [comment]
This is now possible!
