### ISSUE TITLE
0 layers selected

### ISSUE THREAD

**Issue by than0** [hsw107/Photoshop-Export-Layers-to-Files-Fast#130]
I just downloaded the script and thanks a lot for making it. My only problem is that it recognizes my layers but it says none of them are selected and it doesn't export them. It's probably me doing something wrong. I am new to photoshop but I have highlighted them and it still didn't work.
here is an image
![image](https://user-images.githubusercontent.com/48881482/54878803-21951980-4e3a-11e9-8b4b-3a71b5472f0d.png)

**Comment by hsw107** [comment]
So the selected layer thing does seem to not be working, but the script should still export all layers.

**Comment by than0** [comment]
it doesn't, because after i click export and it loads it says that 0 layers have been successfully saved.

**Comment by hsw107** [comment]
What version of photoshop are you on, and do you have a sample psd I could test with? Mine works fine.

**Comment by than0** [comment]
I messed around with it and it works now. I think it was my antivirus that was not allowing the script to run. I have photoshop whitelisted now and its fixed. Thanks a lit for the help though

**Comment by hsw107** [comment]
Thanks for letting me know that helped. Glad it's working for you now!
