### ISSUE TITLE
Photoshop CC 2019 crashes on script run

### ISSUE THREAD

**Issue by XenHat** [hsw107/Photoshop-Export-Layers-to-Files-Fast#131]
Unfortunately I do not have much information to give, I am fairly new to Photoshop.
![image](https://user-images.githubusercontent.com/980408/56461159-38b52180-637c-11e9-86c7-3e9614ad5860.png)

Edit: Crash report contents in a gist as I could not format code inside a collapsible block.
https://gist.github.com/XenHat/2358710fe6887f417d5cacc164b13991

**Comment by hsw107** [comment]
This looks like an issue with your photoshop.

I would google around on:
`photoshop exception 0xc0000005`
or `photoshop EXCEPTION_ACCESS_VIOLATION`

This is likely a preferences, config, or hardware issue.

**Comment by XenHat** [comment]
on a fresh install?

**Comment by hsw107** [comment]
@XenHat Again, this likely is not an issue with the script (otherwise it would be more prevalent) but likely with your machine/photoshop/config/file.  I cannot offer help debugging this since it is not a code error.

**Comment by XenHat** [comment]
I've reset my photoshop configuration, issue still persists 😕
