### ISSUE TITLE
Allow for exporting groups to files

### ISSUE THREAD

**Issue by huckleberrypie** [hsw107/Photoshop-Export-Layers-to-Files-Fast#133]
Would it be possible to merge individual groups and export them as files as well?

**Comment by hsw107** [comment]
Do you mean instead of exporting each layer of a group, it would export the entire group as one image?

**Comment by huckleberrypie** [comment]
Yes, that's what I meant.

**Comment by hsw107** [comment]
I've marked this as an enhancement, and while this isn't possible, there are some possible workarounds.
1) You could use Photoshop Generator to export your folders as images on the fly (https://graphicdesign.stackexchange.com/a/87276/408)
2) You could make a copy of your PSD, and flatten the groups (CTRL+E on a group) and then run the script

**Comment by huckleberrypie** [comment]
Alright, I'll keep those in mind.

**Comment by hsw107** [comment]
Looking again, it looks like you can select `Top Groups as layers` which will merge all groups and then export the layers (and restore it again after the script)
