### ISSUE TITLE
Merge Group option, tif files and more.

### ISSUE THREAD

**Issue by Vincent85-Art** [hsw107/Photoshop-Export-Layers-to-Files-Fast#137]
Hello,

I need a option where the tool merge each folder and then export it to png. Can this option by added? Other thing is TIF going to be supported soon?
And one nice feature would be to export transparency that is present on to the layer as a black and white image next to the layers in a folder. This way other game apps can handle transparency. Hope to hear from you and thank you in advance. Have a nice day!

Cheers,
Vincent

**Comment by hsw107** [comment]
Vincent,

The script has the ability to merge folders and export them already.

Adding TIFF support is possible, I'll add a separate ticket for that, and close this one.

And I'm not sure what you mean by the last suggestion. If you could provide an example an open a separate issue that would be great, although it sounds out of scope.
