### ISSUE TITLE
For easier access why not add to export menu

### ISSUE THREAD

**Issue by schroef** [hsw107/Photoshop-Export-Layers-to-Files-Fast#144]
I was wondering why the code for adding it to the export menu. Is that for keeping it compatible? Im not 100% sure this works with those older versions. But I've seen scripts which have 1997 I the header, so I guess it will work.

Adding it to the export menu allows for faster targeting it.

<img width="736" alt="export layers as images in exportmenu" src="https://user-images.githubusercontent.com/6923008/77448628-66de8500-6dc7-11ea-8ec2-ec6140004fac.png">

**Comment by benjaminv** [comment]
Very intuitive idea indeed. In my case keeping it natively a script makes it more like a customised thing.

**Comment by hsw107** [comment]
You can add the script to the menu by putting into `Photoshop/Preset/Scripts` and restarting Photoshop.

**Comment by schroef** [comment]
> Very intuitive idea indeed. In my case keeping it natively a script makes it more like a customised thing.

Well they are still scripts, it not changed. Plus since its now in the menu you can also add a shortut for even faster usage

**Comment by schroef** [comment]
> You can add the script to the menu by putting into `Photoshop/Preset/Scripts` and restarting Photoshop.

True, but adding to export menu shows what its for plus you keep the list under "scripts" clean. That list can only X amount of scripts.
