### ISSUE TITLE
Group as Foreground

### ISSUE THREAD

**Issue by gijdoul** [hsw107/Photoshop-Export-Layers-to-Files-Fast#145]
Hello,

Is it possible to make group as foreground. I have a mockup with group, inside have different layers and adjustment I want to keep them as it but use this group as foreground then I can export many mockup at a time. I try to merge this group as layer and use as foreground but it not give the result expected. thanks

**Comment by hsw107** [comment]
I'm sorry I'm not sure I understand. Could you provide a .psd example?

**Comment by gijdoul** [comment]
My psd mockup has group with inside several layers with adjustment I want to use the group as foreground but cannot at this time also I cannot merge the group if I merge I lose all adjustments etc ..

**Comment by hsw107** [comment]
Try this:
- Have two groups, your first group (on top) will be everything you want for your foreground
- Group two (on the bottom) will contain all other layers.
- Select group two (click on it)
- Run the script
- In the dialog, under `Export` you should be able to check `Selected group`
- Run the export

This should export all layers in group two, while using group one as a foreground. Is that what you're looking for?
