### ISSUE TITLE
SAVE AS PNG

### ISSUE THREAD

**Issue by rlb11295** [hsw107/Photoshop-Export-Layers-to-Files-Fast#147]
Please consider adding the SAVE AS for PNG option.  The current Photoshop Export As or the option to Save for Web does not transmit the PPI into the PNG  only Save As transmit PPI to the PNG file.   So, if you are working in an original 300PPI file and use this script to save out PNG files, they have the Adobe default 72PPI not 300DPI.  Appreciate someone reviewing this issue and enhancing the script to generate PNGs with the PPI info.

**Comment by hsw107** [comment]
Unfortunately using the Save As functionality is exponentially slower than using the save for web option, so I don't know how much sense it makes it add it to this script, which is aimed at being fast.
