### ISSUE TITLE
Add jpg dimension and resolution function?? 

### ISSUE THREAD

**Issue by baweiland23** [hsw107/Photoshop-Export-Layers-to-Files-Fast#148]
**I would love to use this script to export my layers to files, but I would like to be able to decrease the file size (pixel dimension and resolution for jpg) on export. Would you consider adding this function?** 

Why I would like this - 
I have issues with prefixes when using the native 'layers to files', so I prefer this script. Now if I can just get the file size wrapped up in the same export process that would be IDEAL. My alternatives to modifying the file size include more steps - resize the file before exporting (not ideal), or resizing in Lightroom/other post-export. 

My specific needs - 
I need to export many layers to files - layer name as file name, no prefixes.  
My photoshop file is set up for print - 8.5"x8.5", 300dpi. 
My files are for web - need to be jpg 1024x1024, 72dpi.  

I've never posted to GitHub so hope I'm making this request appropriately! Thank you!

**Comment by hsw107** [comment]
I worry that adding this functionality would be antithetical to the scripts purpose, as I think adding a resize function might slow things down considerably.
