### ISSUE TITLE
Add way to save groups and layers as file names

### ISSUE THREAD

**Issue by bakafoo** [hsw107/Photoshop-Export-Layers-to-Files-Fast#149]
Hey Guys,

Anyway of adjusting to export the groups into the files names as well?  Right now we can save groups as folder but i'm looking to save the groups+layers into the file name. 

instead of the files saved in folders as "../group1/subgroup1/layername.png"
it will save the file as "group1_subgroup1_layername.png"

does this make sense?

**Comment by hsw107** [comment]
This makes sense to me! :)

**Comment by hsw107** [comment]
@bakafoo This is now merged in. Let me know if this addresses your suggestion.

**Comment by bakafoo** [comment]
@hsw107 i just tested this out and it works perfectly.. Thanks for the help
