### ISSUE TITLE
CC crash issue

### ISSUE THREAD

**Issue by PlusMD** [hsw107/Photoshop-Export-Layers-to-Files-Fast#150]
It appears that this script doesn't work with the CC version, however, the inbuilt option is very slow. 
Did anyone find a workaround to get it working for CC or another script that works similar?

**Comment by hsw107** [comment]
@PlusMD Hi there, would you be able to provide both the options you are using for the script as well as a `.psd` that reproduces the issue you are seeing?

I just updated my CC and am able to run the script without issue.

**Comment by andrewdev738** [comment]
For me it also crashes, every time i try to run the script, a dialog with no text and a cancel button appears, it doesn't auto close so i need click it manually, then photoshop crashes. The first time i ran the script it didn't crashed and showed the export dialog, but crashed when processing the layers.

**Comment by PlusMD** [comment]
@hsw107 Hi! I have just got back to looking into this and it seems to be working now. I have seen a fair few crashes but this may be due to the large size of the files that I am using.
