### ISSUE TITLE
Script doesn't work anymore

### ISSUE THREAD

**Issue by Jeg0r** [hsw107/Photoshop-Export-Layers-to-Files-Fast#163]
Hey everyone!

Few months ago the script stopped working for me and I have no idea how to fix it.

When I try to launch the script (tried both scripts>browse and scripts>export layers to files (fast) ) I get an empty error window.
![errr](https://user-images.githubusercontent.com/71220038/132505780-954bea5c-d82f-455c-b243-d856470ede04.PNG)
 THEN one of the two possible things happen:
1) Photoshop crashes without even giving me the usual "send crash report" window
2) The scrip interface pops up, all settings works fine, but when I click "run" photoshop crashes... 

I've tried different versions of Photoshop and different versions of the script, same result all the time.  Tried a clean PS install too, doesn't help.
Is there a chance that it happens because I do not have admin rights on my windows laptop? It looks like the issue is on my side, but I can't figure out how to solve it. 
Any help would me much appreciated!
Thanks!

**Comment by Jeg0r** [comment]
Alright, apologies for disturbing you all.
It turned out to be my hardware issue \ admin rights thing. 
It's a great script, you save millions of human-hours.
Thank you
Best
J

**Comment by philpd85** [comment]
Hi!
I have the same issue. Can you explain how to fix it? I tried running with administrative rights but I still can't get the script to work. It was working amazingly and all of sudden it stopped.
