### ISSUE TITLE
script exports invisible layers

### ISSUE THREAD

**Issue by hepari** [hsw107/Photoshop-Export-Layers-to-Files-Fast#164]
I don't understand why this is happening, but the script exports invisible layers if I have 'all layers' checked.
Also I have to hide the background layer even when the 'bottom layer as background' option is disabled.

![image](https://user-images.githubusercontent.com/10383640/138971994-e08a8bf1-e558-4afa-9955-38b00ca81dc6.png)

I'd appreciate it if you could help as this is a pretty nifty addition to my workflow. Thank you in advance!

**Comment by hsw107** [comment]
Can you see if #171 is the same issue? Closing for now.
