### ISSUE TITLE
Invisible layers are exported

### ISSUE THREAD

**Issue by Clunkton** [hsw107/Photoshop-Export-Layers-to-Files-Fast#171]
I'm trying to export 2 layers (as a single image) from a 47 layer PS file. Even though I have set it to export only the visible layers, when it runs all 47 layers are exported. 

This is using Photoshop 23.0.0 run on macOS 11.6

I've been using this faultlessly for ages, but I updated to 2.4.0 today and now I can't get it to work properly. I've attached a grab of the settings I'm using for reference.

Many thanks

<img width="617" alt="Screenshot 2021-11-03 at 17 25 39" src="https://user-images.githubusercontent.com/93673995/140163601-75201c50-9073-44ec-bbd8-3b0471527c51.png">

**Comment by hsw107** [comment]
Thanks so much for all this information. Sorry to hear you're running into issues.

Do you remember what version worked for you last?

**Comment by hsw107** [comment]
Also are you able to come up with a simple PSD that would reproduce this issue?

Even a screenshot of the layers might be good, like so:
<img width="258" alt="Screen Shot 2021-11-07 at 13 59 33" src="https://user-images.githubusercontent.com/2524299/140661725-0c178b93-bcd5-4430-a022-f2f93516a001.png">

**Comment by Clunkton** [comment]
Hi Hana,

 

Thanks for your response, I’ve realised what is causing the issue. I didn’t have the ‘selected group’ button checked. I’m sure I never had to worry about it in the previous version which is why it didn’t occur to me sooner, but that’s definitely the answer.

 

Thanks again for your time.

Clive

 

 

 

Clive Young
Graphic Designer
E: ***@***.***

 

M: 07917 442084

W: www.onitnow.co.uk

 

 

If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.
 

 

From: Hanna ***@***.***>
Reply to: hsw107/Photoshop-Export-Layers-to-Files-Fast ***@***.***>
Date: Sunday, 7 November 2021 at 21:01
To: hsw107/Photoshop-Export-Layers-to-Files-Fast ***@***.***>
Cc: Clunkton ***@***.***>, Author ***@***.***>
Subject: Re: [hsw107/Photoshop-Export-Layers-to-Files-Fast] Invisible layers are exported (Issue #171)

 

Also are you able to come up with a simple PSD that would reproduce this issue?

Even a screenshot of the layers might be good, like so:

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hepari** [comment]
@hsw107 This seems like the same issue I had, yeah. I expected that 'visible only' would also work with the 'All layers' option. Maybe you could grey out 'visible only' while 'All layers' is selected. Thanks for mentioning me!

**Comment by hsw107** [comment]
Hmm, it should also work for `All Layers`. If that's still an issue I'd love to help out and figure out how to reproduce it.

I did notice that it will export visible layers inside invisible groups, which I made a ticket for here, #174 -- is that the issue you were running into with that?

**Comment by hepari** [comment]
@hsw107

Using this setting, I've tested what gets exported and what doesn't.
![Capture-20211108002](https://user-images.githubusercontent.com/10383640/140786612-4e1c2a7f-02ed-45c7-b1de-40278a452e5d.png)

Result: 

- invisible layer in the invisible group (x)
- visible layer in the invisible group (o)
So yes, the layers in a group don't inherit the visibility of the group they are in.

Here is the file I used to test it. [test.zip](https://github.com/hsw107/Photoshop-Export-Layers-to-Files-Fast/files/7498602/test.zip)

**Comment by Toggenburger** [comment]
Any news on this? It **does not** work with groups as it should. 
I have only 2 layers visible next to 4 invisible layers plus 10 layers divided through 3 invisible folders (Groups).
The 4 invisible layers on top do not get exported, but all 10 layers within the folders do get exported, even though they are set to invisible.
<img width="610" alt="screen settings" src="https://user-images.githubusercontent.com/8643433/182614603-d7607ef3-dcfd-4ce2-981d-6a84846b5170.png">
![screen layers](https://user-images.githubusercontent.com/8643433/182615279-cdc320d5-ea6c-4858-b930-93bcd190615e.png)
