### ISSUE TITLE
Export as BMP 24-bit output is turning to 32-bit depth

### ISSUE THREAD

**Issue by ThisisZeth** [hsw107/Photoshop-Export-Layers-to-Files-Fast#172]
OS: Windows 10 Home 21H2
Photoshop Version: 22.5.1 20210907.r.441 de74e1a  x64
.psd: just a simple image with #FF00FF background (idk about other background)

I'm now working on a project that need to use BMP 24-bit depth images, but this tool exports all files in 32-bit depth instead of 24-bit depth

![Screenshot 2021-11-06 210609](https://user-images.githubusercontent.com/68198919/140612544-7ee5b445-6c06-466a-bd55-e395ae8f9d6c.png)
![Screenshot 2021-11-06 210650](https://user-images.githubusercontent.com/68198919/140612547-039c5aad-175b-4cd6-9e8f-56a7d18c6c9f.png)

**Comment by hsw107** [comment]
May be related to #88

**Comment by ThisisZeth** [comment]
> May be related to #88

is there a way to fix this?

**Comment by hsw107** [comment]
I assume so, but I haven't had a chance to look into this.

**Comment by ThisisZeth** [comment]
> I assume so, but I haven't had a chance to look into this.

That's ok, thanks for the info. For other people who wants to convert this back to 24 bit quickly, just use Format Factory.

**Comment by hsw107** [comment]
Please don't close this issue. I'm hoping this will get fixed eventually. Thanks!

**Comment by hsw107** [comment]
This is now fixed.

**Comment by ThisisZeth** [comment]
> Please don't close this issue. I'm hoping this will get fixed eventually. Thanks!

Sorry, I'm kinda new to Github and don't know much about how to use it. Also, I'm so glad that you fix this.
Thanks a lot :D
