### ISSUE TITLE
full naming controll

### ISSUE THREAD

**Issue by Poppycocks** [hsw107/Photoshop-Export-Layers-to-Files-Fast#71]
For example string interpolation type of resulting files name building would be awesome. %f for underlying file name, %d date, t% time, %n for the loop counter, %l layer name, %c layer count. I also suggest for the loop to start at 0. So for example "%f_bar_%{n+1}" in a file that's name "foo" with 4 layers would result in four files named foo_bar_1, foo_bar_2, foo_bar_3, and foo_bar_4. I mean... I've got other tools for batch renaming but...

**Comment by Koudelka-STS** [comment]
Naming including original filename would an amazing optiont. Otherwise this script is like gazilion times faster than the adobe one! Thank you for that 👍 
If we can get the option for including file name in the new naming, that would be absolutely splendid :)

**Comment by hsw107** [comment]
I've added most of these suggestions in version 2.1, please take a look, and hope these cover what you need!
