### ISSUE TITLE
how I can use that?

### ISSUE THREAD

**Issue by Tiffany777** [hsw107/Photoshop-Export-Layers-to-Files-Fast#77]
how I can use that?
could you make a video to show it?
thx

**Comment by skjorn** [comment]
With all due respect, if you don't know how to use it, you probably don't need it. I doubt any of us two developers have time to do a video, but I'll keep this issue open for a bit to see if someone wants to volunteer. Cheers.

**Comment by Tiffany777** [comment]
thank you so much, I've got to know just now.

Tiffany in Christ

2016-02-04 13:13 GMT-08:00 skjorn <notifications@github.com>:
