### ISSUE TITLE
[REQUEST] Have SaveasPNG option to preserve 300 ppi pngs

### ISSUE THREAD

**Issue by DarioChan** [hsw107/Photoshop-Export-Layers-to-Files-Fast#82]
Hi there,
Your script is my first experience with Photoshop scripts and I am already in love. I can foresee using this script often in the future, however for what I need it is missing one key feature!

**If I use this to export layers as PNGs currently, it will export them at 72ppi. After looking online, it seems this has to do with using a Save/ExportforWeb PNG as opposed to using a standard Saveas PNG. Is it possible to change this, or to have it as another option?**

I tried to change the code a bit to replace Export PNG 24 feature into a Save as PNG, but being a novice, I was unsuccessful.

I'd love to hear your thoughts on this!

**Comment by karingroen** [comment]
I agree, I'm (still) looking for a solution for this problem.  
Otherwise i like the script so far!

**Comment by hsw107** [comment]
Unfortunately as far as I can tell, we are limited to the save for web, which doesn't allow us to specify. Maybe there is a workaround that I'm unaware of but for now I think we're limited to 72ppi.
